Custom widgets
LX-PROJECTS/renthub pull request #14
Opened 2024-05-20 08:55 UTC by divyeshp07

widgets moved to core

2024-05-20 09:07 UTC, Sireen-Official requested changes

2024-05-20 09:07 UTC, Sireen-Official commented on lib/core/widgets/main_btn_widget.dart
> +import 'package:flutter/material.dart';
Optimizations required

2024-05-20 09:07 UTC, Sireen-Official commented on lib/core/widgets/product_card_widget.dart
> +  final double destance;
Spell correction

2024-05-20 09:07 UTC, Sireen-Official commented on lib/core/widgets/product_card_widget.dart
> +    return InkWell(
Need border radius

2024-05-21 04:01 UTC, thadathilsinan requested changes

2024-05-21 04:01 UTC, thadathilsinan commented on lib/core/widgets/main_btn_widget.dart
Use spaces class instead of hardcoded values

2024-05-21 10:30 UTC, Sireen-Official approved these changes

2024-05-21 10:32 UTC, thadathilsinan approved these changes

2024-05-21 10:33 UTC, merged