Home screen UI
LX-PROJECTS/renthub pull request #38
Opened 2024-05-23 12:43 UTC by divyeshp07

Added home screen UI.
Expanded color palette in the core.
Edited existing app color extension.
Renamed "rounded button" to "app icon button" in the core.
Modified dark and light themes.
Added a tab bar widget.

2024-05-23 13:42 UTC, Sireen-Official requested changes
Remove comments, only use comments for documentation

2024-05-23 13:42 UTC, Sireen-Official commented on lib/features/authentication/view/widgets/tabbar_widget.dart
> +              // width: apptheme.spaces.space_700,
Remove this line

2024-05-24 04:07 UTC, thadathilsinan approved these changes

2024-05-24 09:03 UTC, Sireen-Official requested changes

2024-05-24 09:03 UTC, Sireen-Official commented on lib/features/authentication/view/widgets/tabbar_widget.dart
Use the tab bar widget here

2024-05-27 10:12 UTC, Sireen-Official requested changes

2024-05-27 10:12 UTC, Sireen-Official commented on lib/features/authentication/view/pages/home_page.dart
> +      length: 5,
Unnecessary default tab controller, remove it.

2024-05-27 10:12 UTC, Sireen-Official commented on lib/features/authentication/view/pages/home_page.dart
> +                ListView.builder(
Extract this listview builder to one widget

2024-05-27 12:12 UTC, Sireen-Official approved these changes

2024-05-27 12:14 UTC, merged