Completed product add functionalities
LX-PROJECTS/renthub pull request #58
Opened 2024-06-03 10:27 UTC by amalrajkp18

-core :changed add_product_constants name
-removed unused import
-changed add_product_page ui

2024-06-05 06:44 UTC, Sireen-Official requested changes

2024-06-05 06:44 UTC, Sireen-Official commented on lib/features/ads/domain/usecase/add_product_usecase.dart
Use cases must be Callable classes

2024-06-11 05:06 UTC, thadathilsinan approved these changes

2024-06-11 09:43 UTC, Sireen-Official approved these changes

2024-06-11 09:59 UTC, merged